steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/dotted-hope-423417-m6/cloud-run-source-deploy/Briefs', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/dotted-hope-423417-m6/cloud-run-source-deploy/Briefs']
  - name: 'google/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy' 
      - 'infostream' 
      - '--image'
      - 'us-central1-docker.pkg.dev/dotted-hope-423417-m6/cloud-run-source-deploy/Briefs'
      - '--us-central1'
      - 'us-central1' 
      - '--platform' 
      - 'managed'
      - '--allow-unauthenticated' # If you want your service to be publicly accessible

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
