name: Deploy to Cloud Run 

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository code
      - uses: actions/checkout@v3

      # 2. Build the Docker image 
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/dotted-hope-423417-m6/cloud-run-source-deploy/Briefs

      # 3. Deploy to Cloud Run 
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: SERVICE_NAME
          image: us-central1-docker.pkg.dev/dotted-hope-423417-m6/cloud-run-source-deploy/Briefs
          region: us-central1
